=== flashpixx/RoutingSimulation/src/main/xsd/character.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" elementFormDefault="qualified"
    vc:minVersion="1.1">

    <!--  
        https://www.data2type.de/xml-xslt-xslfo/xml-schema/definition-von-eindeutigkeit-s/id-im-vergleich-mit-xs-key/ 
        http://4webmaster.de/wiki/XML-Schema
        https://jaxb.java.net/tutorial/section_2_2_15-Referring-to-Another-XML-Element.html
    -->

    <xs:element name="structure">
        <xs:complexType>
            <xs:all>
                <xs:element maxOccurs="1" minOccurs="1" name="configuration">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="ethnicity">
                                <xs:complexType>
                                    <xs:sequence minOccurs="1">
                                        <xs:element maxOccurs="unbounded" minOccurs="1" name="item">
                                            <xs:complexType>
                                                <xs:attribute name="id"/>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                                <xs:key id="keyethnicity" name="keyethnicity">
                                    <xs:selector xpath="item"/>
                                    <xs:field xpath="@id"/>
                                </xs:key>
                            </xs:element>
                            <xs:element name="motivations" maxOccurs="unbounded" minOccurs="0"
                                type="iname"/>
                            <xs:element name="attack" maxOccurs="unbounded" minOccurs="0"
                                type="iattack"/>
                            <xs:element name="attributes" maxOccurs="unbounded" minOccurs="0"
                                type="iattribut"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="character">
                    <xs:complexType>
                        <xs:sequence maxOccurs="unbounded">
                            <xs:element name="pokemon">
                                <xs:complexType>
                                    <xs:complexContent>
                                        <xs:extension base="ipokemon">
                                            <xs:attribute name="name" type="xs:string"
                                                use="required"/>
                                        </xs:extension>
                                    </xs:complexContent>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:all>
        </xs:complexType>
    </xs:element>

    <xs:attributeGroup name="ivaluetriple">
        <xs:annotation>
            <xs:documentation>definition of the triple for distribution structure</xs:documentation>
        </xs:annotation>
        <xs:attribute name="maximum" type="xs:double" use="required"/>
        <xs:attribute name="minimum" type="xs:double" use="required"/>
        <xs:attribute name="expectedvalue" type="xs:double" use="required"/>
    </xs:attributeGroup>
    <xs:complexType final="restriction" name="ipokemon">
        <xs:sequence maxOccurs="unbounded" minOccurs="1">
            <xs:element name="generation">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element maxOccurs="1" minOccurs="0" name="ethnicity">
                            <xs:complexType>
                                <xs:attribute name="id" use="required"/>
                                <xs:attributeGroup ref="ivaluetriple"/>
                            </xs:complexType>
                        </xs:element>
                        <xs:element maxOccurs="1" minOccurs="0" name="attribut">
                            <xs:complexType>
                                <xs:attribute name="id" use="required"/>
                                <xs:attributeGroup ref="ivaluetriple"/>
                            </xs:complexType>
                        </xs:element>
                        <xs:element maxOccurs="1" minOccurs="0" name="motivation">
                            <xs:complexType>
                                <xs:attribute name="id" use="required"/>
                                <xs:attributeGroup ref="ivaluetriple"/>
                            </xs:complexType>
                        </xs:element>
                        <xs:element name="attack" maxOccurs="1" minOccurs="0">
                            <xs:complexType>
                                <xs:attribute name="id"/>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                </xs:complexType>
                <xs:keyref name="xxx" refer="keyethnicity">
                    <xs:selector xpath="ethnicity"/>
                    <xs:field xpath="@id"/>
                </xs:keyref>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType final="#all" name="iname" abstract="true">
        <xs:sequence>
            <xs:element name="name"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="iattribut" abstract="true" final="#all">
        <xs:all>
            <xs:element id="keyattribute" maxOccurs="1" minOccurs="1" name="name" type="xs:ID"/>
            <xs:element maxOccurs="1" minOccurs="1" name="access">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="read, write"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:all>
    </xs:complexType>
    <xs:complexType name="iattack" abstract="true" final="#all">
        <xs:all>

            <xs:element maxOccurs="1" minOccurs="1" name="distance" type="xs:positiveInteger"/>
            <xs:element maxOccurs="1" minOccurs="1" name="cost">
                <xs:simpleType>
                    <xs:restriction base="xs:double">
                        <xs:minExclusive value="0"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element maxOccurs="unbounded" minOccurs="1" name="damage">
                <xs:complexType>
                    <xs:attribute name="id" type="xs:IDREF" use="required"/>
                    <xs:attribute name="value" use="required">
                        <xs:simpleType>
                            <xs:restriction base="xs:double">
                                <xs:minExclusive value="0"/>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:attribute>
                </xs:complexType>
            </xs:element>
        </xs:all>
    </xs:complexType>
</xs:schema>

=== flashpixx/RoutingSimulation/src/main/resources/org/lightjason/examples/pokemon/datasource/character.xml
<?xml version="1.0" encoding="UTF-8"?>
<structure xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="../../../../../../../main/xsd/character.xsd">
    <configuration>


        <ethnicity>
            <item id="normal"/>
            <item id="fighting"/>
            <item id="flying"/>
            <item id="poison"/>
            <item id="ground"/>
            <item id="rock"/>
            <item id="bug"/>
            <item id="ghost"/>
            <item id="steel"/>
            <item id="fire"/>
            <item id="water"/>
            <item id="grass"/>
            <item id="electric"/>
            <item id="psychic"/>
            <item id="ice"/>
            <item id="dragon"/>
            <item id="dark"/>
            <item id="fairy"/>
        </ethnicity>


        <attribute>
            <item id="energy" agentaccess="read"/>
            <item id="mind" agentaccess="read"/>
            <item id="health" agentaccess="read"/>
            <item id="maximumexperience" agentaccess="read"/>
            <item id="experience" agentaccess="read"/>
            <item id="attack" agentaccess="read"/>
            <item id="defense" agentaccess="read"/>
            <item id="weight" agentaccess="read"/>
            <item id="height" agentaccess="read"/>
            <item id="viewrange" agentaccess="read"/>
            <item id="viewangle" agentaccess="read"/>
            <item id="maximumspeed" agentaccess="read"/>
            <item id="speed" agentaccess="write"/>
            <item id="nearby" agentaccess="write"/>
        </attribute>


        <motivation>
            <item id="hunt"/>
            <item id="fight"/>
            <item id="help"/>
            <item id="ignorance"/>
            <item id="cautiousness"/>
            <item id="elopement"/>
            <item id="cure"/>
        </motivation>


        <attack>
            <!-- === normal ================================================================================================================================ -->
            <item id="scratch" distance="1" accuracy="1" energycost="0.05">
                <damage id="health" value="0.3"/>
            </item>

            <item id="tackle" distance="1" accuracy="1" energycost="0.05">
                <damage id="health" value="0.3"/>
            </item>

            <item id="slash" distance="1" accuracy="1" energycost="0.1">
                <damage id="health" value="0.4"/>
            </item>

            <item id="slam" distance="1" accuracy="0.9" energycost="0.1">
                <damage id="health" value="0.4"/>
                <damage id="mind" value="0.1"/>
            </item>

            <item id="headbut" distance="1" accuracy="1" energycost="0.1">
                <damage id="health" value="0.3"/>
                <damage id="mind" value="0.2"/>
            </item>

            <item id="pound" distance="1" accuracy="1" energycost="1">
                <damage id="health" value="0.4"/>
                <damage id="defense" value="0.1"/>
            </item>

            <item id="cometpunch" distance="2" accuracy="0.8" energycost="1">
                <damage id="health" value="0.4"/>
                <damage id="defense" value="0.1"/>
            </item>

            <item id="drillpeck" distance="3" accuracy="0.8" energycost="0.05">
                <damage id="health" value="0.8"/>
            </item>

            <item id="gust" distance="4" accuracy="1" energycost="0.05">
                <damage id="health" value="0.4"/>
            </item>

            <item id="wingattack" distance="3" accuracy="1" energycost="0.1">
                <damage id="health" value="0.6"/>
            </item>

            <item id="skyattack" distance="5" accuracy="0.9" energycost="0.15">
                <damage id="health" value="1"/>
            </item>

            <!-- === fire ================================================================================================================================== -->
            <item id="ember" distance="2" accuracy="1" energycost="0.05">
                <damage id="health" value="0.4"/>
            </item>

            <item id="firespin" distance="3" accuracy="0.85" energycost="0.5">
                <damage id="health" value="0.35"/>
                <damage id="speed" value="0.1"/>
            </item>

            <item id="flamethrower" distance="5" accuracy="1" energycost="0.1">
                <damage id="health" value="0.8"/>
                <damage id="defense" value="0.1"/>
            </item>

            <item id="fireblast" distance="8" accuracy="0.85" energycost="0.15">
                <damage id="health" value="1"/>
            </item>


            <!-- === water ================================================================================================================================= -->
            <item id="bubble" distance="2" accuracy="1" energycost="0.05">
                <damage id="health" value="0.3"/>
                <damage id="mind" value="0.1"/>
            </item>

            <item id="watergun" distance="3" accuracy="1" energycost="0.1">
                <damage id="health" value="0.4"/>
            </item>

            <item id="bubblebeam" distance="3" accuracy="1" energycost="0.15">
                <damage id="health" value="0.65"/>
            </item>

            <item id="surf" distance="4" accuracy="1" energycost="0.15">
                <damage id="health" value="0.15"/>
            </item>

            <item id="hydropump" distance="3" accuracy="0.8" energycost="0.05">
                <damage id="health" value="1"/>
            </item>


            <!-- === electric ============================================================================================================================== -->
            <item id="thunderwave" distance="3" accuracy="1" energycost="0.05">
                <damage id="mind" value="0.1"/>
            </item>

            <item id="thundershock" distance="4" accuracy="1" energycost="0.05">
                <damage id="health" value="0.4"/>
            </item>
            
            <item id="thunderbolt" distance="4" accuracy="1" energycost="0.1">
                <damage id="health" value="0.8"/>
            </item>
            
            <item id="thunder" distance="5" accuracy="1" energycost="0.15">
                <damage id="health" value="1"/>
            </item>
            
            
            <!-- === grass ================================================================================================================================= -->
            <item id="stunspore" distance="2" accuracy="0.95" energycost="0.05">
                <damage id="mind" value="0.1"/>
            </item>
            
            <item id="vinewhip" distance="3" accuracy="1" energycost="0.05">
                <damage id="health" value="0.25"/>
            </item>            

            <item id="petaldance" distance="2" accuracy="1" energycost="0.1">
                <damage id="health" value="0.7"/>
            </item>            

            <item id="razorleaf" distance="4" accuracy="0.95" energycost="0.15">
                <damage id="health" value="0.45"/>
            </item>            

            <item id="solarbeam" distance="5" accuracy="1" energycost="0.15">
                <damage id="health" value="1"/>
            </item>            


            <!-- === ice =================================================================================================================================== -->
            <item id="haze" distance="3" accuracy="1" energycost="0.05">
                <damage id="mind" value="0.1"/>
            </item>
            
            <item id="aurorabeam" distance="5" accuracy="1" energycost="0.1">
                <damage id="health" value="0.65"/>
            </item>

            <item id="blizzard" distance="3" accuracy="0.7" energycost="0.1">
                <damage id="health" value="0.1"/>
            </item>
            
            <item id="icebeam" distance="4" accuracy="1" energycost="0.15">
                <damage id="health" value="0.9"/>
                <damage id="defense" value="0.3"/>
            </item>
            
            
            <!-- === fighting ================================================================================================================================== -->
            <item id="doublekick" distance="2" accuracy="1" energycost="0.05">
                <damage id="health" value="0.3"/>
                <damage id="defense" value="0.1"/>
            </item>
            
            <item id="karatechop" distance="2" accuracy="1" energycost="0.05">
                <damage id="health" value="0.3"/>
                <damage id="defense" value="0.1"/>
            </item>
            
            <item id="doubleslap" distance="2" accuracy="1" energycost="0.05">
                <damage id="health" value="0.4"/>
                <damage id="defense" value="0.1"/>
            </item>
            
            <item id="jumpkick" distance="3" accuracy="0.95" energycost="0.1">
                <damage id="health" value="0.5"/>
                <damage id="defense" value="0.1"/>
            </item>
            
            <item id="highjumpkick" distance="3" accuracy="0.95" energycost="0.15">
                <damage id="health" value="0.7"/>
                <damage id="defense" value="0.1"/>
            </item>
            
            <item id="seismictoss" distance="4" accuracy="1" energycost="0.15">
                <damage id="health" value="1"/>
                <damage id="defense" value="0.1"/>
            </item>
            
            
            <!-- === poison ==================================================================================================================================== -->
